name: Python application test with Github Actions
on: [push]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: action/setup-python@v1
      with:
        python-version: 3.12
    - name: Install dependencies
      run: 
        make install
